# version : '3.8'
services:
  app:
    build: .
    container_name: multi-tenant
    ports:
      - "3999:3999"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      SQL_DB_NAME_FRESH: ${SQL_DB_NAME_FRESH}
      SQL_DB_NAME_MEAL: ${SQL_DB_NAME_MEAL}
      SQL_DB_NAME_TIFFIN: ${SQL_DB_NAME_TIFFIN}
      SQL_DB_HOST: ${SQL_DB_HOST}
      SQL_DB_USERNAME: ${SQL_DB_USERNAME}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}
  
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    restart: always
    env_file:
      - .env
    environment:
      MySQL_ROOT_PASSWORD: ${MySQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: