version: '3.8'

services:
  app:
    build: .
    container_name: multi-tenant
    ports:
      - "3999:3999"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PORT: 3999
      SQL_DB_NAME_FRESH: freshbite_db
      SQL_DB_NAME_MEAL: mealkart_order_db
      SQL_DB_NAME_TIFFIN: tastytiffin_db
      SQL_DB_HOST: mysql
      SQL_DB_USERNAME: root
      SQL_DB_PASSWORD: MySQL@123

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQL@123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
